"""Optional JavaScript rendering, following the repo's "stdlib floor, upgrade if
installed" pattern (see ``site_snapshot/pdf_writer.py``).

A static fetch sees what the server sends. On sites that build their content in
the browser that is not what a reader sees: measured on one real page, the
served HTML carried 17 tables and no buttons while the rendered DOM had 23
tables and 78 buttons, all of them generated by the page's own script.

Turning on ``render`` drives a headless browser through Playwright and hands the
crawler the post-JavaScript DOM instead. It is strictly opt-in: Playwright is a
heavy dependency (a browser download, not just a wheel), rendering is an order
of magnitude slower than a GET, and it forfeits conditional-GET incrementality
because there is no ETag on a rendered DOM. When Playwright is absent or the
browser fails to launch, :class:`Renderer` reports itself unavailable and the
crawl silently continues with static fetches.

The SSRF guard still applies: every URL is validated through the same
``fetcher.guard_host`` check before the browser is pointed at it, and the
browser is launched with no proxy and a fixed viewport.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Dict, Optional

from ..site_snapshot.fetcher import USER_AGENT, BlockedHostError, guard_host

logger = logging.getLogger(__name__)

DEFAULT_VIEWPORT = {"width": 1280, "height": 900}


@dataclass
class RenderResult:
    html: str = ""
    status: int = 0
    final_url: str = ""
    error: Optional[str] = None
    elapsed_ms: int = 0
    console_errors: int = 0


class Renderer:
    """Headless-browser page renderer. Construct once per crawl, close at the end."""

    def __init__(
        self,
        *,
        wait_ms: int = 600,
        timeout: float = 30.0,
        wait_until: str = "networkidle",
        user_agent: str = USER_AGENT,
    ):
        self.wait_ms = wait_ms
        self.timeout_ms = int(timeout * 1000)
        self.wait_until = wait_until
        self.user_agent = user_agent
        self.unavailable_reason: Optional[str] = None
        self._playwright = None
        self._browser = None
        self._context = None

    # ------------------------------------------------------------------ #
    def available(self) -> bool:
        """Is a browser ready? Launches lazily on the first call."""
        if self._context is not None:
            return True
        if self.unavailable_reason is not None:
            return False
        try:
            from playwright.sync_api import sync_playwright
        except Exception as exc:
            self.unavailable_reason = (
                "Playwright is not installed — falling back to static fetches "
                "(pip install playwright && playwright install chromium). "
                f"[{type(exc).__name__}]"
            )
            return False
        try:
            self._playwright = sync_playwright().start()
            self._browser = self._playwright.chromium.launch(headless=True)
            self._context = self._browser.new_context(
                user_agent=self.user_agent,
                viewport=DEFAULT_VIEWPORT,
                java_script_enabled=True,
            )
            self._context.set_default_timeout(self.timeout_ms)
        except Exception as exc:
            self.unavailable_reason = f"Could not launch a browser: {exc}"
            self.close()
            return False
        return True

    def render(self, url: str) -> RenderResult:
        """Return the post-JavaScript DOM for ``url``."""
        import time

        start = time.monotonic()
        result = RenderResult(final_url=url)
        if not self.available():
            result.error = self.unavailable_reason
            return result
        try:
            guard_host(url)  # same SSRF gate as the static fetcher
        except BlockedHostError as exc:
            result.error = f"blocked: {exc}"
            return result

        page = None
        try:
            page = self._context.new_page()
            errors: list = []
            page.on("pageerror", lambda _e: errors.append(1))
            response = page.goto(url, wait_until=self.wait_until)
            if self.wait_ms:
                page.wait_for_timeout(self.wait_ms)
            result.html = page.content()
            result.status = response.status if response is not None else 200
            result.final_url = page.url or url
            result.console_errors = len(errors)
        except Exception as exc:
            result.error = f"{type(exc).__name__}: {exc}"
        finally:
            if page is not None:
                try:
                    page.close()
                except Exception:  # pragma: no cover - teardown best effort
                    pass
        result.elapsed_ms = int((time.monotonic() - start) * 1000)
        return result

    def close(self) -> None:
        for attr in ("_context", "_browser", "_playwright"):
            obj = getattr(self, attr, None)
            if obj is None:
                continue
            try:
                obj.stop() if attr == "_playwright" else obj.close()
            except Exception:  # pragma: no cover - teardown best effort
                pass
            setattr(self, attr, None)

    def __enter__(self) -> "Renderer":
        return self

    def __exit__(self, *exc) -> None:
        self.close()

    def stats(self) -> Dict[str, Any]:
        return {
            "available": self._context is not None,
            "reason": self.unavailable_reason,
            "wait_until": self.wait_until,
            "wait_ms": self.wait_ms,
        }
